const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{performance}=require('node:perf_hooks');
const root=__dirname,model=fs.readFileSync(path.join(root,'models','acoustic-fleet.html'),'utf8'),context={};vm.createContext(context);vm.runInContext(model.slice(model.indexOf(' const calibration='),model.indexOf(' const root='))+'\nthis.api={precomputeRoutes,makeDemand,run};',context);
const api=context.api,seeds=Array.from({length:30},(_,index)=>741+index),population=[40,40,40,220,220,220,40,40,40],acoustic=api.precomputeRoutes(),periodCount=120,lateWindow=24,demands=[25,30,35],fleets=[2,3,4],targets=[14.05,14.5,15,15.5,16,17],rolling={rollingLookahead:3,rollingExposureWeight:1,rollingWorkloadWeight:.3,rollingFairnessWeight:1};
const gates={minimumCompletionRate:.99,maximumLateQueueSlope:.1,maximumLateMeanWaitMinutes:30,maximumOldestQueueAgeMinutes:480,maximumDestinationCompletionGap:.02,maximumLateBudgetSd:1,maximumLateSaturationShare:.25,minimumPassingSeedShare:.95};
function sum(values){return values.reduce((a,b)=>a+b,0);}function mean(values){return sum(values)/values.length;}function sd(values){if(values.length<2)return 0;const average=mean(values);return Math.sqrt(sum(values.map(value=>(value-average)**2))/(values.length-1));}function slope(values){const xm=(values.length-1)/2,ym=mean(values),den=sum(values.map((_,index)=>(index-xm)**2));return sum(values.map((value,index)=>(index-xm)*(value-ym)))/den;}
const rows=[];
for(const demandMean of demands)for(const fleetSize of fleets)for(const target of targets)for(const seed of seeds){
 const demand=api.makeDemand(demandMean,seed,[.2,.6,.2],periodCount),requestCounts=[0,0,0];for(const period of demand)for(const request of period)requestCounts[request.destination]++;
 const cfg={delay:1,gain:.6,damping:.5,targetEquivalent:target,initialBudgetEquivalent:20,acousticWeightKm:.35,fleetSize,chargerCapacity:fleetSize,...rolling},started=performance.now(),history=api.run(4,cfg,demand,population,acoustic),runtimeMs=performance.now()-started,late=history.slice(-lateWindow),requests=sum(requestCounts),dispatched=sum(history.map(state=>state.dispatched)),lateRequests=sum(demand.slice(-lateWindow).map(period=>period.length)),lateDispatched=sum(late.map(state=>state.dispatched)),dispatchCounts=[0,1,2].map(destination=>sum(history.map(state=>state.dispatchedByDestination[destination]))),destinationRates=dispatchCounts.map((value,index)=>value/requestCounts[index]),completion=dispatched/requests,lateQueueSlope=slope(late.map(state=>state.queueEnd)),lateWeightedWait=sum(late.map(state=>state.meanWait*state.dispatched)),lateMeanWait=lateDispatched?lateWeightedWait/lateDispatched:0,lateBudgets=late.map(state=>state.budgetsEquivalent[4]),controllerSd=sd(lateBudgets),lateSaturationShare=lateBudgets.filter(value=>value>=39.999).length/lateWindow,destinationGap=Math.max(...destinationRates)-Math.min(...destinationRates),gatePass=completion>=gates.minimumCompletionRate&&lateQueueSlope<=gates.maximumLateQueueSlope&&lateMeanWait<=gates.maximumLateMeanWaitMinutes&&history.at(-1).oldestQueueAge<=gates.maximumOldestQueueAgeMinutes&&destinationGap<=gates.maximumDestinationCompletionGap&&controllerSd<=gates.maximumLateBudgetSd&&lateSaturationShare<=gates.maximumLateSaturationShare;
 rows.push({demand:demandMean,fleet_size:fleetSize,charger_capacity:fleetSize,target,seed,periods:periodCount,requests,dispatched,completion_rate:completion,late_service_ratio:lateDispatched/lateRequests,final_queue:history.finalQueue,late_queue_slope:lateQueueSlope,late_mean_wait_minutes:lateMeanWait,late_p95_wait_mean:mean(late.map(state=>state.p95Wait)),final_oldest_queue_age:history.at(-1).oldestQueueAge,north_completion_rate:destinationRates[0],central_completion_rate:destinationRates[1],south_completion_rate:destinationRates[2],destination_completion_gap:destinationGap,late_budget_mean:mean(lateBudgets),late_budget_sd:controllerSd,late_budget_saturation_share:lateSaturationShare,late_exposure_mean:mean(late.map(state=>state.usedEquivalent[4])),gate_pass:gatePass?1:0,runtime_ms:runtimeMs});
}
const groups=new Map();for(const row of rows){const key=`${row.demand}|${row.fleet_size}|${row.target}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}const numeric=Object.keys(rows[0]).filter(field=>typeof rows[0][field]==='number'&&!['demand','fleet_size','charger_capacity','target','seed','periods'].includes(field)),summaries=[];for(const group of groups.values()){const first=group[0],summary={demand:first.demand,fleet_size:first.fleet_size,charger_capacity:first.charger_capacity,target:first.target,runs:group.length,periods:first.periods};for(const field of numeric){const values=group.map(row=>row[field]),average=mean(values),half=1.96*sd(values)/Math.sqrt(values.length);summary[field+'_mean']=average;summary[field+'_ci_low']=average-half;summary[field+'_ci_high']=average+half;}summary.configuration_gate_pass=summary.gate_pass_mean>=gates.minimumPassingSeedShare?1:0;summaries.push(summary);}summaries.sort((a,b)=>a.demand-b.demand||a.fleet_size-b.fleet_size||a.target-b.target);
function csv(data){const fields=Object.keys(data[0]);return fields.join(',')+'\n'+data.map(row=>fields.map(field=>String(row[field])).join(',')).join('\n')+'\n';}const out=path.join(root,'results');fs.writeFileSync(path.join(out,'phase_e11_target_runs.csv'),csv(rows));fs.writeFileSync(path.join(out,'phase_e11_target_summary.csv'),csv(summaries));const metadata={experiment:'Phase E11 target and capacity refinement',generated_at:new Date().toISOString(),total_runs:rows.length,unique_configurations:summaries.length,seeds:[seeds[0],seeds.at(-1)],periods:periodCount,late_window_periods:lateWindow,demands,fleets,targets,charger_rule:'One charger per drone',policy:'P3-D0.50',gain:.6,delay:1,damping:.5,rolling_dispatch:rolling,progression_gates:gates};fs.writeFileSync(path.join(out,'phase_e11_target_metadata.json'),JSON.stringify(metadata,null,2)+'\n');console.log(`Wrote ${rows.length} target-capacity runs and ${summaries.length} summaries.`);
