const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{performance}=require('node:perf_hooks');
const root=__dirname,model=fs.readFileSync(path.join(root,'models','acoustic-fleet.html'),'utf8'),context={};vm.createContext(context);vm.runInContext(model.slice(model.indexOf(' const calibration='),model.indexOf(' const root='))+'\nthis.api={precomputeRoutes,makeDemand,run};',context);
const api=context.api,seeds=Array.from({length:30},(_,index)=>701+index),population=[40,40,40,220,220,220,40,40,40],acoustic=api.precomputeRoutes(),periodCount=120,lateWindow=24,demands=[10,15,18,20,22,25,30,45],fleets=[1,2,3,4,6],rolling={rollingLookahead:3,rollingExposureWeight:1,rollingWorkloadWeight:.3,rollingFairnessWeight:1};
const stability={maxLateQueueSlope:0.1,maxFinalQueuePeriods:1,maxOldestQueueAgeMinutes:480,minCompletionRate:.95,minStableSeedShare:.9};
function sum(values){return values.reduce((a,b)=>a+b,0);}function mean(values){return sum(values)/values.length;}function sd(values){if(values.length<2)return 0;const average=mean(values);return Math.sqrt(sum(values.map(value=>(value-average)**2))/(values.length-1));}function slope(values){const xm=(values.length-1)/2,ym=mean(values),den=sum(values.map((_,index)=>(index-xm)**2));return sum(values.map((value,index)=>(index-xm)*(value-ym)))/den;}
const rows=[],periodRows=[];
for(const demandMean of demands)for(const fleetSize of fleets)for(const seed of seeds){
 const demand=api.makeDemand(demandMean,seed,[.2,.6,.2],periodCount),requests=demand.flat().length,cfg={delay:1,gain:.6,damping:.5,targetEquivalent:14.05,initialBudgetEquivalent:20,acousticWeightKm:.35,fleetSize,chargerCapacity:fleetSize,...rolling},started=performance.now(),history=api.run(4,cfg,demand,population,acoustic),runtimeMs=performance.now()-started,late=history.slice(-lateWindow),dispatched=sum(history.map(state=>state.dispatched)),lateRequests=sum(demand.slice(-lateWindow).map(period=>period.length)),lateDispatched=sum(late.map(state=>state.dispatched)),lateQueueSlope=slope(late.map(state=>state.queueEnd)),finalQueue=history.finalQueue,postSurgeMean=1.6*demandMean,completion=dispatched/requests,stable=lateQueueSlope<=stability.maxLateQueueSlope&&finalQueue<=stability.maxFinalQueuePeriods*postSurgeMean&&history.at(-1).oldestQueueAge<=stability.maxOldestQueueAgeMinutes&&completion>=stability.minCompletionRate,weightedWait=sum(history.map(state=>state.meanWait*state.dispatched)),lateWeightedWait=sum(late.map(state=>state.meanWait*state.dispatched)),requestCounts=[0,0,0],dispatchCounts=[0,1,2].map(destination=>sum(history.map(state=>state.dispatchedByDestination[destination])));for(const period of demand)for(const request of period)requestCounts[request.destination]++;
 rows.push({demand:demandMean,fleet_size:fleetSize,charger_capacity:fleetSize,seed,periods:periodCount,requests,dispatched,completion_rate:completion,late_service_ratio:lateDispatched/lateRequests,final_queue:finalQueue,late_queue_slope:lateQueueSlope,mean_wait_minutes:dispatched?weightedWait/dispatched:0,late_mean_wait_minutes:lateDispatched?lateWeightedWait/lateDispatched:0,late_p95_wait_mean:mean(late.map(state=>state.p95Wait)),final_oldest_queue_age:history.at(-1).oldestQueueAge,north_completion_rate:dispatchCounts[0]/requestCounts[0],central_completion_rate:dispatchCounts[1]/requestCounts[1],south_completion_rate:dispatchCounts[2]/requestCounts[2],late_budget_mean:mean(late.map(state=>state.budgetsEquivalent[4])),late_budget_sd:sd(late.map(state=>state.budgetsEquivalent[4])),late_exposure_mean:mean(late.map(state=>state.usedEquivalent[4])),stable:stable?1:0,runtime_ms:runtimeMs});
 for(const state of history)periodRows.push({demand:demandMean,fleet_size:fleetSize,seed,period:state.period,dispatched:state.dispatched,queue_end:state.queueEnd,mean_wait_minutes:state.meanWait,p95_wait_minutes:state.p95Wait,oldest_queue_age:state.oldestQueueAge,central_budget:state.budgetsEquivalent[4],central_use:state.usedEquivalent[4]});
}
const groups=new Map();for(const row of rows){const key=`${row.demand}|${row.fleet_size}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}const numeric=Object.keys(rows[0]).filter(field=>typeof rows[0][field]==='number'&&!['demand','fleet_size','charger_capacity','seed','periods'].includes(field)),summaries=[];
for(const group of groups.values()){const first=group[0],summary={demand:first.demand,fleet_size:first.fleet_size,charger_capacity:first.charger_capacity,runs:group.length,periods:first.periods};for(const field of numeric){const values=group.map(row=>row[field]),average=mean(values),half=1.96*sd(values)/Math.sqrt(values.length);summary[field+'_mean']=average;summary[field+'_ci_low']=average-half;summary[field+'_ci_high']=average+half;}summary.configuration_stable=summary.stable_mean>=stability.minStableSeedShare?1:0;summaries.push(summary);}summaries.sort((a,b)=>a.demand-b.demand||a.fleet_size-b.fleet_size);
const periodGroups=new Map();for(const row of periodRows){const key=`${row.demand}|${row.fleet_size}|${row.period}`;if(!periodGroups.has(key))periodGroups.set(key,[]);periodGroups.get(key).push(row);}const periodSummaries=[];for(const group of periodGroups.values()){const first=group[0],summary={demand:first.demand,fleet_size:first.fleet_size,period:first.period,runs:group.length};for(const field of ['dispatched','queue_end','mean_wait_minutes','p95_wait_minutes','oldest_queue_age','central_budget','central_use']){const values=group.map(row=>row[field]),average=mean(values),half=1.96*sd(values)/Math.sqrt(values.length);summary[field+'_mean']=average;summary[field+'_ci_low']=average-half;summary[field+'_ci_high']=average+half;}periodSummaries.push(summary);}
function csv(data){const fields=Object.keys(data[0]);return fields.join(',')+'\n'+data.map(row=>fields.map(field=>String(row[field])).join(',')).join('\n')+'\n';}const out=path.join(root,'results');fs.writeFileSync(path.join(out,'phase_e11_capacity_runs.csv'),csv(rows));fs.writeFileSync(path.join(out,'phase_e11_capacity_summary.csv'),csv(summaries));fs.writeFileSync(path.join(out,'phase_e11_period_summary.csv'),csv(periodSummaries));const metadata={experiment:'Phase E11 pilot capacity envelope',generated_at:new Date().toISOString(),total_runs:rows.length,unique_configurations:summaries.length,period_summaries:periodSummaries.length,seeds:[seeds[0],seeds.at(-1)],periods:periodCount,late_window_periods:lateWindow,demands,fleets,charger_rule:'One charger per drone',policy:'P3-D0.50',target:14.05,gain:.6,delay:1,damping:.5,rolling_dispatch:rolling,stability_gates:stability};fs.writeFileSync(path.join(out,'phase_e11_metadata.json'),JSON.stringify(metadata,null,2)+'\n');console.log(`Wrote ${rows.length} capacity runs, ${summaries.length} summaries, and ${periodSummaries.length} period summaries.`);
